[package]
name = "bevy_networking_turbulence"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[features]
default = ["use-udp"]
use-udp = ["naia-server-socket/use-udp"]
use-webrtc = ["naia-server-socket/use-webrtc"]

[dependencies]
bevy = { path = "../bevy", version = "0.2" }
turbulence = { path = "../turbulence", version = "0.1.2-alpha.0" }
naia-client-socket = { path = "../naia-socket/client", version = "0.3" }
bytes = "0.5"
log = "0.4"
futures-lite = "1.4"
crossbeam-channel = "0.4.4"
cfg-if = "0.1"
instant = "0.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
naia-server-socket = { path = "../naia-socket/server", version = "0.3" }
async-compat = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
simple_logger = "1"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2"
