[package]
name = "bevy_networking_turbulence"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[dependencies]
bevy_app = { version = "0.2", default-features = false }
turbulence = "0.1"
naia-server-socket = { version = "0.3", features = ["use-webrtc"] }
naia-client-socket = "0.3"
