[package]
name = "bevy_networking_turbulence"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[dependencies]
bevy = { path = "../bevy", version = "0.2", default-features = false }
turbulence = "0.1"
naia-server-socket = { version = "0.3", features = ["use-webrtc"] }
naia-client-socket = { version = "0.3" }
log = "0.4"
async-compat = "0.1"
crossbeam-channel = "0.4.4"

[dev-dependencies]
simple_logger = "1"
